### ISSUE TITLE
Powerline symbols not rendered when text value is empty

### ISSUE THREAD

**Issue by mwasowski** [JanDeDobbeleer/oh-my-posh#1137]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Can't say when, but my prompt got a bit broken by one of the updates. I have the following segment:
```
        {
          "background": "#d3d7cf",
          "foreground": "#000000",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "prefix": "",
            "postfix": "",
            "text": ""
          },
          "style": "powerline",
          "type":"text"
        },
        {
          "background": "#d3d7cf",
          "foreground": "#000000",
           "invert_powerline": true,
          "leading_diamond": "",
          "properties": {
            "prefix": "",
            "postfix": "  "
          },
          "style": "diamond",
          "type": "time"
        }
```
It was working as expected before showing time like this:
![obraz](https://user-images.githubusercontent.com/1921808/139472628-5fb9049d-6795-4e32-aa6a-6b8f7de2c611.png)

Now it looks like this:
![obraz](https://user-images.githubusercontent.com/1921808/139472662-9ebbd1e3-690c-46d5-acec-f5ab9229889a.png)

It looks like the powerline symbol is not rendered when the `text` is empty. When I set it to a space " ", it works but adds fair amount of space:
![obraz](https://user-images.githubusercontent.com/1921808/139472841-18489f52-0fbb-4d80-8ac4-1bb34ee6908c.png)

I know that you'll probably say that I should use "leading_diamond" property, but that does not produce the effect I'm going for. At first I thought it did:
![obraz](https://user-images.githubusercontent.com/1921808/139473072-49325229-db47-4e30-b9bd-def94cb0cb03.png)

But well..it doesn't ;)
![obraz](https://user-images.githubusercontent.com/1921808/139473158-6ade14c9-6b12-4f32-bef5-e5b2482008bc.png)

### Version

5.16.2

### Theme

Powerline10k_rainbow with minor modifications

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by lnu** [comment]
should be fixed by https://github.com/JanDeDobbeleer/oh-my-posh/pull/1134
keep your template as before and it will work once the pull is merged.

**Comment by JanDeDobbeleer** [comment]
@mwasowski that's probably the issue @lnu found and what's supposedly going to be fixed [here](https://github.com/JanDeDobbeleer/oh-my-posh/pull/1134).

**Comment by mwasowski** [comment]
Awesome, thanks! This looks like it indeed, let's close this and track it there 👍

**Comment by JanDeDobbeleer** [comment]
@mwasowski was the reopen on purpose?

**Comment by mwasowski** [comment]
@JanDeDobbeleer Yes. I closed it before testing but 5.16.3 did not fix this for me.
So with no preceding segment it looks like this:
![obraz](https://user-images.githubusercontent.com/1921808/139486365-c33454e4-ded8-4c82-af61-08b2f93ad388.png)
And with like this.
![obraz](https://user-images.githubusercontent.com/1921808/139486431-0d44ab03-4e77-4a76-87c4-855e370a94dd.png)

**Comment by JanDeDobbeleer** [comment]
I'll check, but that one does look like something else than the what @lnu fixed. I can have a look tomorrow.

**Comment by mwasowski** [comment]
I'll look at it tomorrow as well. It feels like it's related to the text property, like it can't be empty/null or it will not render the item. Having preceding segment kinda fixes it.

**Comment by lnu** [comment]
It's related to this change(text segment not rendered if empty) https://github.com/JanDeDobbeleer/oh-my-posh/commit/d0816773a51c0ab62016d91294902fe7bd38ed91
Your sample works if I revert it

this works for example:
```
{
          "background": "#d3d7cf",
          "foreground": "#000000",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "prefix": "",
            "postfix": "",
            "text": ""
          },
          "style": "powerline",
          "type":"text"
        },
        {
          "background": "#d3d7cf",
          "foreground": "#000000",
           "invert_powerline": true,
           "powerline_symbol": "",
          "leading_diamond": "",
          "properties": {
            "prefix": "",
            "postfix": "  "
          },
          "style": "diamond",
          "type": "time"
        }
```

**Comment by JanDeDobbeleer** [comment]
@mwasowski can you give me your full config? There's a clean way to do this, but I noticed a new bug ;-) If I have your full config I can fix everything.

**Comment by JanDeDobbeleer** [comment]
@mwasowski when the change above lands, this seems to work like a charm:

```json
{
    "style": "plain",
    "type": "exit",
    "background": "#AF3322",
    "foreground": "#ffffff",
    "properties": {
        "prefix": "<#AF3322,transparent></> "
    }
},
{
    "background": "#d3d7cf",
    "foreground": "#000000",
    "invert_powerline": true,
    "leading_diamond": "<#d3d7cf,inherit></>",
    "properties": {
        "prefix": " ",
        "postfix": "  "
    },
    "style": "diamond",
    "type": "time"
}
```

**Comment by mwasowski** [comment]
@JanDeDobbeleer There you go
https://pastebin.com/Qa4JUS70

**Comment by JanDeDobbeleer** [comment]
@mwasowski here you go, diamond is what you want all the way down ;-)

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh3/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "newline": true,
      "segments": [],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "background": "#d3d7cf",
          "foreground": "#000000",
          "style": "diamond",
          "type": "os"
        },
        {
          "background": "#3465a4",
          "foreground": "#e4e4e4",
          "powerline_symbol": "",
          "properties": {
            "home_icon": "~",
            "prefix": "  ",
            "style": "full"
          },
          "style": "powerline",
          "type": "path"
        },
        {
          "background": "#4e9a06",
          "foreground": "#000000",
          "powerline_symbol": "",
          "properties": {
            "ahead_and_behind_color": "#f26d50",
            "ahead_color": "#89d1dc",
            "behind_color": "#4e9a06",
            "branch_icon": " ",
                  "display_status": true,
            "display_stash_count": true,
            "display_upstream_icon": true,
            "local_changes_color": "#c4a000",
            "stash_count_icon": " ",
            "status_colors_enabled": true
          },
          "style": "powerline",
          "type": "git"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        {
          "background": "#689f63",
          "foreground": "#ffffff",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "display_version": true,
            "postfix": " "
          },
          "style": "diamond",
          "type": "node"
        },
        {
          "background": "#00acd7",
          "foreground": "#111111",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "display_version": true,
            "postfix": " "
          },
          "style": "diamond",
          "type": "go"
        },
        {
          "background": "#FFDE57",
          "foreground": "#111111",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "display_mode": "files",
            "display_version": true,
            "display_virtual_env": false,
            "postfix": " "
          },
          "style": "diamond",
          "type": "python"
        },
        {
          "background": "#AE1401",
          "foreground": "#ffffff",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "display_mode": "files",
            "display_version": true,
            "postfix": " "
          },
          "style": "diamond",
          "type": "ruby"
        },
        {
          "background": "#FEAC19",
          "foreground": "#ffffff",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "display_mode": "files",
            "display_version": false,
            "postfix": " "
          },
          "style": "diamond",
          "type": "azfunc"
        },
        {
          "background_templates": [
            "{{if contains \"default\" .Profile}}#FFA400{{end}}",
            "{{if contains \"Michał\" .Profile}}#f1184c{{end}}"
          ],
          "foreground": "#ffffff",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "display_default": false,
            "postfix": " "
          },
          "style": "diamond",
          "type": "aws"
        },
        {
          "background": "#000000",
          "foreground": "#d3d7cf",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "always_enabled": false,
            "color_background": true,
            "display_exit_code": true,
            "error_color": "#cc2222"
          },
          "style": "diamond",
          "type": "exit"
        },
        {
          "background": "#ffff66",
          "foreground": "#111111",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "root_icon": ""
          },
          "style": "diamond",
          "type": "root"
        },
        {
          "background": "#c4a000",
          "foreground": "#000000",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "always_enabled": false,
            "threshold": 100,
            "postfix": "  "
          },
          "style": "diamond",
          "type": "executiontime"
        },
        {
          "background": "#d3d7cf",
          "foreground": "#000000",
          "leading_diamond": "<background,inherit></>",
          "properties": {
            "prefix": " ",
            "postfix": "  "
          },
          "style": "diamond",
          "type": "time"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "foreground": "#007ACC",
          "properties": {
            "prefix": "",
            "postfix": "",
            "text": "❯"
          },
          "style": "plain",
          "type": "text"
        }
      ],
      "type": "prompt"
    }
  ],
  "console_title": true,
  "console_title_style": "template",
  "console_title_template": "{{ .Shell }} in {{ .Folder }}",
  "final_space": true,
  "transient_prompt": {
    "background": "transparent",
    "foreground": "#007ACC",
    "template": "❯ "
  }
}
```

**Comment by mwasowski** [comment]
Yeah! That fixes the issue, but now I see this 🤔 
![obraz](https://user-images.githubusercontent.com/1921808/139535166-9a6908f5-fbf0-4994-be6e-aeca43b1cfe2.png)
😆

**Comment by mwasowski** [comment]
And it's specific to Error, because for example this renders fine:
![obraz](https://user-images.githubusercontent.com/1921808/139535221-fc6a7b88-51fb-4bfc-b1ac-cd9037920eec.png)

**Comment by JanDeDobbeleer** [comment]
@mwasowski my bad, just swap the error segment's `leading_diamond` to this: `"leading_diamond": "<background,inherit></>",`, I also updated the comment above as in fact they can all have that setting.

**Comment by mwasowski** [comment]
@JanDeDobbeleer That did the trick! And no need to apologize! Thank you for all the great work!

And generally..can I use this
```
"<background,inherit></>"
```
instead of:
```
"<#ffff66,inherit></>"
```
It's cleaner and less likely to be messed up when changing colors ;)

**Comment by mwasowski** [comment]
Ah, I have an issue with reading and understanding apparently :D You wrote I can use background everywhere 🤦‍♂️

Thanks again!
