### ISSUE TITLE
Conda Environment showing nothing in the Python Segment

### ISSUE THREAD

**Issue by LeoCalbi** [JanDeDobbeleer/oh-my-posh#133]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When activating a conda environment the python segment disappears, the base environment is show as expected.
![image](https://user-images.githubusercontent.com/16137253/98487741-17997780-2225-11eb-8285-8194ed4c20a6.png)

### Environment

- Oh my Posh version: 3.29.3
- Theme: powelevel10k_classic with a python segment
- Operating System: Windows 10
- Shell: Powershell 7
- Terminal: Windows Terminal

### Steps to Reproduce

1. Go in a folder with a .py file
2. Activate a conda environment

**Expected behavior:**
The enviroment name and associated python version as the "base" one.

**Actual behavior:**
Nothing is shown.

**Comment by JanDeDobbeleer** [comment]
I look for the `CONDA_ENV_PATH` and `CONDA_DEFAULT_ENV` environment variables, can you see if they hold a value? Unless `python(3) --version` doesn't output a value anymore in this case, which would also stop the segment from rendering entirely.

**Comment by LeoCalbi** [comment]
First of all thanks for the fast replay.
This is the situation:

- `python --version` works in both the base and the environment

- `CONDA_ENV_PATH` isn't set in both cases 

- `CONDA_DEFAULT_ENV` works as expected.

Could the problem be the version of Python in the case of the environment? 
Because of the _:: Anaconda, Inc._ ?

![image](https://user-images.githubusercontent.com/16137253/98527185-fc595700-227a-11eb-88f7-c0cb33bc2d9b.png)

**Comment by JanDeDobbeleer** [comment]
> Could the problem be the version of Python in the case of the environment?
> Because of the _:: Anaconda, Inc._ ?

I'll test this, could be. I would expect it to show `flatland_rl 3.6.8 :: Anaconda, Inc.`

```golang
func TestPythonWriterEnabledWithCondaDefaultEnvAnacondaInc(t *testing.T) {
	args := newPythonArgs()
	args.condaDefaultName = "flatland_rl"
	args.pythonVersion = "Python 3.6.8 :: Anaconda, Inc."
	expected := "flatland_rl 3.6.8 :: Anaconda, Inc."
	python := bootStrapPythonTest(args)
	assert.True(t, python.enabled())
	assert.Equal(t, expected, python.string())
}
```

This passes, so something else is going on.

The only thing I see right now is that this one could fail somehow:

```golang
if !p.env.hasFiles("*.py") && !p.env.hasFiles("*.ipynb") {
    return false
}
```

**Comment by LeoCalbi** [comment]
Really don't know what to say.
The folder contains various *.py files, and as I cd into it the _base_ environment show itself in the python segment.
Don't know how activating an environment would cause it to lose track of these files.

Even leaving and returning to the folder with the *.py files, with the _flatland-rl_ environment already active didn't change the outcome.
![image](https://user-images.githubusercontent.com/16137253/98531197-4bee5180-2280-11eb-9764-47edf8ab7941.png)

**Comment by JanDeDobbeleer** [comment]
I'll have to set up one myself to debug this realtime ;-)

**Comment by LeoCalbi** [comment]
Thanks again! Let me know if I can help in any way 😉

**Comment by JanDeDobbeleer** [comment]
I can't reproduce this on MacOS, so maybe it's a Windows thing. Stay tuned.

**Comment by JanDeDobbeleer** [comment]
~~There's something about the Python segment that is off, I can reproduce this on my Mac as well.~~

<img width="852" alt="afbeelding" src="https://user-images.githubusercontent.com/2492783/98554427-fb3b2080-22a0-11eb-97c0-cb9ee91ac4f6.png">

To Windows it is...

**Comment by JanDeDobbeleer** [comment]
@LeoCalbi can you update to the latest version and see if that changes something?

**Comment by LeoCalbi** [comment]
I updated but the problem persist with the `flatland-rl` environment.
![image](https://user-images.githubusercontent.com/16137253/98586212-b32ff400-22c8-11eb-9333-cf2323860370.png)
Then tried to make a new `test` one on the fly, and it works as expected😊 but still no luck with the other.
Do you think there is a problem with the name of the env?
![image](https://user-images.githubusercontent.com/16137253/98586492-115cd700-22c9-11eb-9d9c-a921adfb0662.png)

**Comment by JanDeDobbeleer** [comment]
That seems like most logical explanation yeah. I'll try that!

**Comment by LeoCalbi** [comment]
I have tried to create a new env named `test-env` and even that works.

But I've found out something that might be interesting, if I create the environment using a different python version like 3.6.8 with a environment.yml file but with the names `test` or `test-env` or whatever else, it shows nothing, while if I use python 3.8.3 it works.

Here is my sample enviroment.yml

```yaml
name: test-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - psutil==5.7.2
  - pip==20.2.3
  - python==3.6.8 #3.8.3
  - autopep8==1.5.4
  - tabulate==0.8.7
```

**Comment by LeoCalbi** [comment]
I updated to the latest beta 3.36.1 and now it works. 🎉 
In case of flatland-rl environment it still doesn't render the python version, just the name, but it's still much more better than before.
Thanks for the amazing work! 
If you need me to test whatever on my windows setup, even in the future, I'm available to help!

**Comment by MythreyaK** [comment]
Doesn't seem to work on python's `venv` too. I'm on version `3.51.0`, installed from `PSGallery`.

![image](https://user-images.githubusercontent.com/26112391/101785909-515ee600-3b23-11eb-8471-f7b6c82ac0b8.png)

**Comment by JanDeDobbeleer** [comment]
Are there python files in that directory @MythreyaK ?

**Comment by MythreyaK** [comment]
Ahh, I see, there need to be python files! My bad. Yeah it shows up now, but the bit on the starting `(env-name)` is still there. Is that expected behavior?

**Comment by JanDeDobbeleer** [comment]
@MythreyaK can you clarify what you see vs what you expect to avoid me saying silly things?

**Comment by MythreyaK** [comment]
What I see, 
![](https://user-images.githubusercontent.com/26112391/101785909-515ee600-3b23-11eb-8471-f7b6c82ac0b8.png)

What I thought I'd see (like in the previous version) something like this in the prompt
![image](https://user-images.githubusercontent.com/26112391/101928279-6444e980-3bfb-11eb-95e9-55a31d52de06.png)

**Comment by JanDeDobbeleer** [comment]
Ok, so when you're in a folder with python files this context should show. It supports a few virtualenv tools, when enabled it shows the one with the first match.

**Comment by MythreyaK** [comment]
Yep, I'll manually set the env variable to prevent `env`at the start from showing up. 

![image](https://user-images.githubusercontent.com/26112391/101976063-a441b600-3c67-11eb-8e42-d9cdc2bb5d8e.png)

**Comment by JanDeDobbeleer** [comment]
That .env at the start is done by the tool you are using, which one is it? As I can't manipulate that it needs to be disabled in the tool itself.

**Comment by MythreyaK** [comment]
Yeah I mean to say, that is added by the python virtual environment tooling (the activate script). I dealt with this by adding `$env:VIRTUAL_ENV_DISABLE_PROMPT="True"` in my powershell profile. Not sure how the others don't have the leading prompt from `virtualenv` or `venv` tooling.

**Comment by wtfzambo** [comment]
Sorry for reopening this, but I'm facing a somewhat similar problem as @MythreyaK as I don't know how to address.

When using conda, one is supposed to run `conda init powershell`, after installation.
This modifies powershell $profile, adding a line at the botton that runs a couple of scripts. Among other things, this adds `(env_name)` to the beginning of the prompt and sets an env variable that defines the name of the current active environment: `$Env:CONDA_PROMPT_MODIFIER`.

However the now added `(base)` becomes very redundant (and kinda ugly), when using oh-my-posh. Any idea how to prevent it from appearing? I already tried changing `.condarc` and set `conda config --set changeps1 True`, but on windows that disables any sort of prompt modification, because I think that setting is meant to work only on *nix machines.

See screenshot:
![image](https://user-images.githubusercontent.com/47462792/117549592-8f612700-b03b-11eb-90a9-ac439811fe78.png)

**Comment by MythreyaK** [comment]
@wtfzambo Try this, *outside* a conda env
```
PS > echo '$env:VIRTUAL_ENV_DISABLE_PROMPT="True"' >> $PROFILE
```

Restart powershell. Should fix the issue.

**Comment by wtfzambo** [comment]
@MythreyaK tried that, both at beginning and end of my powershell profile, but nothing changed somehow. I resorted to editing `Conda.psm1` manually inside the condabin directory.

Not the most ideal solution tho.

**Comment by JanDeDobbeleer** [comment]
@wtfzambo this is an issue that should be raised at Conda. They need to adjust their powershell script to allow disabling this.

**Comment by MythreyaK** [comment]
Oh @wtfzambo my apologies, that snippet was for a different vnev management tool. 

From the `conda.psm1` [here](https://github.com/conda/conda/blob/ed96a06244eb820781dc872eb381f51b95ee48ae/conda/shell/condabin/Conda.psm1#L277-L284), I think removing the env variable should do, by setting the `CONDA_PROMPT_MODIFIER` to `null`, `$env:CONDA_PROMPT_MODIFIER=$null`. But this won't work if the script sets and prints the prompt before or after this workaround is executed. 

If that's the case, `conda` needs to support a way to detect custom prompts in use. @JanDeDobbeleer , is there an env variable that `oh-my-posh` sets that can perhaps be used to feature-detect this in the scripts that conda uses? For example, in posix shells, `conda` checks for the presence of `POWERLINE_COMMAND` before shell prompt modification.

**Comment by JanDeDobbeleer** [comment]
@MythreyaK we can set env vars in the bootstrap but that still doesn't guarantee anything. There's also zero consistency when it comes to Pythons stack and this specific issue, making it even more challenging.

**Comment by MythreyaK** [comment]
I was thinking of suggesting a pull-request to conda, similar to how they check for `POWERLINE_COMMAND` in posix shells. Since `oh-my-posh` seems to handle all python env tooling and modifies the prompt accordingly, conda can just skip setting the prompt if some check is satisfied. Using some env var could do.

**Comment by JanDeDobbeleer** [comment]
@MythreyaK added.

**Comment by wtfzambo** [comment]
> 
> 
> @MythreyaK added.

So, I did `Update-Module oh-my-posh` after that commit but I'm still facing that issue with Anaconda (env) appearing before the powerline. Is it supposed to fix it or am I missing something?

**Comment by JanDeDobbeleer** [comment]
@wtfzambo we can't fix this on our end. If, and that's a big if, the specific tooling you use respects the env vars, it will not show. Otherwise you need to look at the specific logic inside the .ps1 used for your conda env to see if there's a way to disable it.

**Comment by MythreyaK** [comment]
@wtfzambo we'll update you once the fix is tested.

**Comment by wtfzambo** [comment]
**EDIT as of 2022-04-05**:

I seem to have fixed the problem by setting `changeps1: false` in .condarc.
To do it from the CLI: `conda config --set changeps1 false`
Conda version: 4.11.0

-----------

@JanDeDobbeleer @MythreyaK

I see!

I was under the (mistaken) assumption that the above commit would address this issue. No big deal, I'll just edit `conda.psm1` to just not print the env in the prompt.

For anyone looking for a solution, the simplest way is to edit `Conda.psm1` at `$Env:_CONDA_ROOT/shell/condabin`.

You want to comment out this line: `$Env:CONDA_PROMPT_MODIFIER | Write-Host -NoNewline` (row 280), like this:

```powershell
function Add-CondaEnvironmentToPrompt() {
    function global:prompt() {
        if ($Env:CONDA_PROMPT_MODIFIER) {
            # $Env:CONDA_PROMPT_MODIFIER | Write-Host -NoNewline
        }
        CondaPromptBackup;
    }
}
```

Keep in mind that if you update conda, this file will most probably be renewed and you'll have to make the change again.

**Comment by JanDeDobbeleer** [comment]
I can also set `ONDA_PROMPT_MODIFIER` to `false`

**Comment by manmartgarc** [comment]
Thanks @wtfzambo, that fix does work but you're right. It breaks on update. @JanDeDobbeleer just to make sure I understand, this is a problem on conda's side? Is there any sort of workaround that can be done on this side?

**Comment by JanDeDobbeleer** [comment]
It's completely in conda's hands to nog override a prompt when certain variables are set. I already added everything I could, they have to allow a switch upstream (I could propose a PR for that).

**Comment by JanDeDobbeleer** [comment]
@manmartgarc according to [this](https://github.com/conda/conda/blob/ad6fcd7dd09485286f60d8bd6d03cf9813234027/conda/shell/condabin/Conda.psm1#L272), you should be able to set `$CondaModuleArgs.ChangePs1 = $false` in your `$PROFILE` to stop conda from messing with your prompt.

**Comment by manmartgarc** [comment]
Oh! I will try that today and let you know how it works out. Thanks!

**Comment by manmartgarc** [comment]
I am getting this error:

![image](https://user-images.githubusercontent.com/29613324/161608974-072066ee-cf40-4671-9786-7c0db6121a56.png)

I am guessing that the `$CondaModuleArgs` object is created inside the `Conda.ps1` script?

**Comment by JanDeDobbeleer** [comment]
@manmartgarc could be true.

**Comment by manmartgarc** [comment]
Yeah, it's actually hardcoded in `conda-hook.ps1` and passed as an argument. I tried setting line 6 to:

> $CondaModuleArgs = @{ChangePs1 = $False}

But nothing changes 🤔 . I'll keep using @wtfzambo's fix for now.

**Comment by wtfzambo** [comment]
> Yeah, it's actually hardcoded in `conda-hook.ps1` and passed as an argument. I tried setting line 6 to:
> 
> > $CondaModuleArgs = @{ChangePs1 = $False}
> 
> But nothing changes 🤔 . I'll keep using @wtfzambo's fix for now.

@JanDeDobbeleer , @manmartgarc , hey, I just saw the notification. I seem to have fixed the problem by setting `changeps1: false` in .condarc. To do it from the CLI: `conda config --set changeps1 false`. I am currently not using omp, but I don't think it matters as for what regards this specific issue.

Conda version: 4.11.0.

See attached screen:

![image](https://user-images.githubusercontent.com/47462792/161785071-88c6e567-5cbf-4a2a-a18c-4e911c41f6b0.png)

**Comment by manmartgarc** [comment]
> > Yeah, it's actually hardcoded in `conda-hook.ps1` and passed as an argument. I tried setting line 6 to:
> > > $CondaModuleArgs = @{ChangePs1 = $False}
> > 
> > 
> > But nothing changes 🤔 . I'll keep using @wtfzambo's fix for now.
> 
> @JanDeDobbeleer , @manmartgarc , hey, I just saw the notification. I seem to have fixed the problem by setting `changeps1: false` in .condarc. To do it from the CLI: `conda config --set changeps1 false`. I am currently not using omp, but I don't think it matters as for what regards this specific issue.
> 
> Conda version: 4.11.0.
> 
> See attached screen:
> 
> ![image](https://user-images.githubusercontent.com/47462792/161785071-88c6e567-5cbf-4a2a-a18c-4e911c41f6b0.png)

This works! 👏
